/******************
=== Example 1 ===
******************/
SET NOCOUNT ON
SET XACT_ABORT ON
GO
DROP TABLE IF EXISTS TT1, TT2, TT3
GO
CREATE TABLE TT1 (a int NOT NULL CHECK (a > 0))
CREATE TABLE TT2 (a int NOT NULL CHECK (a > 0))
CREATE TABLE TT3 (a int NOT NULL CHECK (a > 0))
Go

BEGIN TRANSACTION 
INSERT TT1 (a)
   SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3
INSERT TT2 (a)
   SELECT 11 UNION ALL SELECT -12 UNION ALL SELECT 13
INSERT TT3 (a)
   SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23
COMMIT TRANSACTION
go
SELECT a FROM TT1
SELECT a FROM TT2
SELECT a FROM TT3
go

/*
TT1 & TT3 Popucated, TT2 NOT
Change to 

SET XACT_ABORT ON

NO tables populated
*/

/******************
=== Example 1 ===
******************/

SET NOCOUNT ON
SET XACT_ABORT ON
GO

DROP TABLE IF EXISTS TT1
GO
CREATE TABLE TT1 (a int)
GO

BEGIN TRANSACTION 
	SELECT 1/0			-- Not Batch_Abort
	--SELECT 'A' + 1		-- Batch_Abort
INSERT TT1 VALUES(1)
COMMIT TRANSACTION

SELECT * FROM TT1
